package QueSorbetoDataBase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENT".
 */
public class Client {

    private Long id;
    /** Not-null value. */
    private String idClient;
    /** Not-null value. */
    private String name;
    private String phone;
    private String address;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Client() {
    }

    public Client(Long id) {
        this.id = id;
    }

    public Client(Long id, String idClient, String name, String phone, String address) {
        this.id = id;
        this.idClient = idClient;
        this.name = name;
        this.phone = phone;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdClient() {
        return idClient;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdClient(String idClient) {
        this.idClient = idClient;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
