package QueSorbetoDataBase;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import QueSorbetoDataBase.Client;
import QueSorbetoDataBase.Product;
import QueSorbetoDataBase.Invoice;
import QueSorbetoDataBase.InvoiceDetail;

import QueSorbetoDataBase.ClientDao;
import QueSorbetoDataBase.ProductDao;
import QueSorbetoDataBase.InvoiceDao;
import QueSorbetoDataBase.InvoiceDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clientDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig invoiceDaoConfig;
    private final DaoConfig invoiceDetailDaoConfig;

    private final ClientDao clientDao;
    private final ProductDao productDao;
    private final InvoiceDao invoiceDao;
    private final InvoiceDetailDao invoiceDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        invoiceDaoConfig = daoConfigMap.get(InvoiceDao.class).clone();
        invoiceDaoConfig.initIdentityScope(type);

        invoiceDetailDaoConfig = daoConfigMap.get(InvoiceDetailDao.class).clone();
        invoiceDetailDaoConfig.initIdentityScope(type);

        clientDao = new ClientDao(clientDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        invoiceDao = new InvoiceDao(invoiceDaoConfig, this);
        invoiceDetailDao = new InvoiceDetailDao(invoiceDetailDaoConfig, this);

        registerDao(Client.class, clientDao);
        registerDao(Product.class, productDao);
        registerDao(Invoice.class, invoiceDao);
        registerDao(InvoiceDetail.class, invoiceDetailDao);
    }
    
    public void clear() {
        clientDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        invoiceDaoConfig.getIdentityScope().clear();
        invoiceDetailDaoConfig.getIdentityScope().clear();
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public InvoiceDao getInvoiceDao() {
        return invoiceDao;
    }

    public InvoiceDetailDao getInvoiceDetailDao() {
        return invoiceDetailDao;
    }

}
