package QueSorbetoDataBase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INVOICE_DETAIL".
 */
public class InvoiceDetail {

    private Long id;
    /** Not-null value. */
    private String idInvoice;
    private int quantity;
    /** Not-null value. */
    private String idProduct;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public InvoiceDetail() {
    }

    public InvoiceDetail(Long id) {
        this.id = id;
    }

    public InvoiceDetail(Long id, String idInvoice, int quantity, String idProduct) {
        this.id = id;
        this.idInvoice = idInvoice;
        this.quantity = quantity;
        this.idProduct = idProduct;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdInvoice() {
        return idInvoice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdInvoice(String idInvoice) {
        this.idInvoice = idInvoice;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /** Not-null value. */
    public String getIdProduct() {
        return idProduct;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
