package QueSorbetoDataBase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INVOICE".
 */
public class Invoice {

    private Long id;
    /** Not-null value. */
    private String idClient;
    /** Not-null value. */
    private String idInvoice;
    private Integer invoiceNumber;
    private java.util.Date invoiceDate;
    private Double invoiceTotalPrice;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Invoice() {
    }

    public Invoice(Long id) {
        this.id = id;
    }

    public Invoice(Long id, String idClient, String idInvoice, Integer invoiceNumber, java.util.Date invoiceDate, Double invoiceTotalPrice) {
        this.id = id;
        this.idClient = idClient;
        this.idInvoice = idInvoice;
        this.invoiceNumber = invoiceNumber;
        this.invoiceDate = invoiceDate;
        this.invoiceTotalPrice = invoiceTotalPrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdClient() {
        return idClient;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdClient(String idClient) {
        this.idClient = idClient;
    }

    /** Not-null value. */
    public String getIdInvoice() {
        return idInvoice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdInvoice(String idInvoice) {
        this.idInvoice = idInvoice;
    }

    public Integer getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(Integer invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public java.util.Date getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(java.util.Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public Double getInvoiceTotalPrice() {
        return invoiceTotalPrice;
    }

    public void setInvoiceTotalPrice(Double invoiceTotalPrice) {
        this.invoiceTotalPrice = invoiceTotalPrice;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
