package QueSorbetoDataBase;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCT".
 */
public class Product {

    private Long id;
    /** Not-null value. */
    private String idProduct;
    private String name;
    /** Not-null value. */
    private String code;
    private double Price;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    public Product(Long id, String idProduct, String name, String code, double Price) {
        this.id = id;
        this.idProduct = idProduct;
        this.name = name;
        this.code = code;
        this.Price = Price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdProduct() {
        return idProduct;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdProduct(String idProduct) {
        this.idProduct = idProduct;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getCode() {
        return code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCode(String code) {
        this.code = code;
    }

    public double getPrice() {
        return Price;
    }

    public void setPrice(double Price) {
        this.Price = Price;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
